[package]
name = "dive-computer-proto"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0.219", features = ["derive"], default-features = false }
postcard = { version = "1.0.0", default-features = false }
dive-deco = { version = "5.2.2", features = ["serde"] }
